server:
  port: 8080 #the default port used for zuul service

spring:
  cloud:
    gateway:
      routes:
      - id: test-service
        uri: http://localhost:8081
        predicates:
          - Path=/test
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
