server:
  port: 8080 #the default port used for zuul service

spring:
  cloud:
    config:
      uri: http://localhost:8888  #where the config-service is running
      fail-fast: true             #the service will not run if it can't reach the config-service
  gateway:
    routes:
      - id: test-service
        uri: http://localhost:8081
        predicates:
          - Path=/test
